# https://hub.docker.com/r/liquibase/liquibase
# https://hub.docker.com/r/webdevops/liquibase

services:
  liquibase:
    image: liquibase/liquibase
#    image: webdevops/liquibase:mysql
    container_name: liquibase
    environment:
      LIQUIBASE_URL: jdbc:mysql://host.docker.internal:3306/liquibase
      LIQUIBASE_USERNAME: liquibase
      LIQUIBASE_PASSWORD: password
      LIQUIBASE_DRIVER: com.mysql.jdbc.Driver
      LIQUIBASE_CHANGELOG: /liquibase/changelog/db/changelog.yaml
      LIQUIBASE_CLASSPATH: /liquibase/changelog
    entrypoint: /bin/sh
    volumes:
      - ./changelog:/liquibase/changelog
